[project]
name = "close-my-bank-account"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pytz>=2025.2",
    "google-generativeai>=0.5.4",
]
